### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-async-iteration#25]
- [x] Add for-await parsing support to Babylon
- [ ] Add a transform plugin for for-await and async generators

**Comment by benjamingr** [comment]
Anything I can experiment with?

**Comment by zenparsing** [comment]
I wanted to give the value unwrapping semantics a little more thought before I started working on the transform plugin. I'm pretty sure that the current semantics are the best option, though, and I'll post in the other thread with my rationale soon.

In the meantime, you can play around in the [esdown repl](https://zenparsing.github.io/esdown/repl/), or run code directly with [esdown](https://github.com/zenparsing/esdown/).

**Comment by zenparsing** [comment]
PR submitted to babel: https://github.com/babel/babel/pull/3473.  I'm not sure when it will land, since it requires a version bump for babylon.

**Comment by GabrielRatener** [comment]
In Bizubee I implement async generator functions using the following support code

```js
getObservableCtrl() {
	let first = true, promises = [];
	let onsend, onsendfail;
	let onnext, onnextfail;
	let done = function(value) {
		onsend({
			done: true,
			value: value
		});
	};
	let observable = {
		[symbols.observer] () {
			return observable;
		},
		next(value) {
			if (first) {
				if (value !== undefined)
					throw new Error('First sent value must not exist!');

				let p = new Promise(function(win, fail) {
					onsend = win;
					onsendfail = fail;
				});

				first = false;
				api.code().then(done);

				return p;
			} else {
				let p = new Promise(function(win, fail) {
					onsend = win;
					onsendfail = fail;
				});

				onnext(value);

				return p;
			}
		}
	};

	let api = {
		send(value) {
			onsend({
				value: value,
				done: false
			});

			let npromise = new Promise(function(win, fail) {
				onnext = win;
				onnextfail = fail;
			});

			return npromise;
		},
		observable: observable
	};

	return api;
}
```

Bizubee targets ES6, whereas Babel and most other transpilers target ES5 or ES3. So the support code would probably have to be modified accordingly.

But using the same general api async generator functions can be implemented

Where this
```js
// silly, but proves the point
async function* fibonacciAsync() {
	var [current, next] = await Promise.resolve([0, 1]);
	while (true) {
		yield current;
		[current, next] = await Promise.resolve([next, current + next]);
	}
}

```

could become

```js
function fibonacciAsync () {
	// create instance of observable controller
	var _ctrl = _supportLib.getObservableCtrl();

	// create async function from generator function...
	_ctrl.code = _supportLib.async(function* () {
		var [current, next] = yield Promise.resolve([0, 1]);
		while (true) {
			yield _ctrl.send(current);
			[current, next] = yield Promise.resolve([next, current + next]);
		}
	}).bind(this); // bind to this scope of fibonacciAsync call

	return _ctrl.observable;
}
```

Just sayin

**Comment by isiahmeadows** [comment]
I'll note a key difference between async iterators and observables:

- Async iterators are inherently lazy and pull-based, where you ask for the data. These are useful for dealing with asynchronous, but non-real-time data like from reading local files.
- Observables are inherently eager and push-based, where the data is handed to you, regardless of how ready you are. These are useful for dealing with real-time data like UI events (you're notified as soon as the action occurs, whether you're ready or not).

It's possible to convert one to the other, but it will make things far less efficient.

- You can read a file in its entirety, but it's far more memory efficient if you handle a few bytes at a time, when you are ready for them. This is why `fs.createReadStream("file.txt").pipe(fs.createWriteStream("dest.txt"))` is far more efficient than `fs.writeFileSync("dest.txt", fs.readFileSync("file.txt"))`.
- You can always make a lazy stream of UI events, but you'll have to buffer them, because you can't control when they're generated. If you don't handle them eventually (even if this means ignoring them), especially if the events in question are frequently generated, you will inevitably run into memory issues.

So both are useful in different contexts. Here's some other examples, in browsers and in Node:

- In a browser, an async iterator can model the list of posts for a live Twitter or Facebook feed. Each post has to be asynchronously gathered, but you only need to request what can actually be displayed. Deleted posts don't have to be removed from the browser in a time-sensitive fashion, so the list can be considered immutable.
- In Node, an async iterator can model an infinite sequence of tokens for a two-factor auth mechanism. You read the token when you need it, but you don't need notified of anything (other than when the token is ready).
- In a browser, an observable can model changes to an app's state. This is the core concept of Flux, just under different terminology. When the app state changes, you'll want to make sure the UI reflects the new state.
- In Node, an observable can model incoming server requests. You have to handle them somehow, even if it's by doing nothing.

I could make similar comparisons to arrays (here's a list of values) vs iterables (take as many as you need).

**Comment by hzoo** [comment]
https://github.com/babel/babel/pull/3473 is merged and released. I did notice it wasn't added to the stage-2 preset (only the package.json) so need to release that again https://github.com/babel/babel/pull/4611

**Comment by domenic** [comment]
@hzoo thanks so much for your work here! To be clear, "babel-plugin-transform-async-generator-functions" also transforms for-await-of statements, not just async generator functions, right?

I'd welcome your help on a pull request to reword the section at https://github.com/tc39/proposal-async-iteration#implementation-status into something that would be more helpful to Babel users.

Closing this since the task is done \o/

**Comment by hzoo** [comment]
Yeah, it does both (through using a helper package called `babel-helper-remap-async-to-generator`) but for users it's the `babel-plugin-transform-async-generator-functions` plugin.
