### ISSUE TITLE
eslint plugin

### ISSUE THREAD

**Issue by aaronshaf** [tc39/proposal-async-iteration#58]
Does anyone know if there is an eslint plugin for this yet?

**Comment by domenic** [comment]
Hi @aaronshaf,

This doesn't appear to be a specification issue, so I'm going to close it. Feel free to use the closed thread as a discussion forum, if you wish.

**Comment by BenoitZugmeyer** [comment]
Since babel now supports async-iteration, you can use [babel-eslint](https://github.com/babel/babel-eslint/) to support the new syntax. It works great!

I guess it's a bit too soon for Acorn (the parser eslint is using underneath) to support this. To my knowledge they aren't supporting unfinished proposals.
